name: CICD pipeline using Maven and Docker
on:
 push:
  branches:
   - master
jobs:
 deploy:
  env:
   imageName: "myactionimagejava"
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: Install java and Maven
     uses: actions/setup-java@v3
     with:
      java-version: '11'
      distribution: 'temurin'
      cache: 'maven'
   - name: setup-Docker
     uses: docker/setup-buildx-action@v3
   - name: Build with Maven
     run: mvn package
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME}}
       password: ${{ secrets.DOCKERHUB_TOKEN}}
   - name: Build the image and push to dockerhub 
     uses: docker/build-push-action@v3
     with:
       context: .
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{ env.imageName }}:latest
   - name: run the image
     run: docker run -d -P ${{ secrets.DOCKERHUB_USERNAME}}/${{ env.imageName }}:latest
